setwd("~/NETELabs_CaseStudies/assembly/interim_results/")
t_alem <- read.csv("alem_pubref.csv",stringsAsFactors=FALSE)
t_imat <- read.csv("imat_pubref.csv",stringsAsFactors=FALSE)
t_nela <- read.csv("nela_pubref.csv",stringsAsFactors=FALSE)
t_ramu <- read.csv("ramu_pubref.csv",stringsAsFactors=FALSE)
t_suni <- read.csv("suni_pubref.csv",stringsAsFactors=FALSE)
t_list <- list()
t_list[[1]] <- unique(union(t_alem$cited_pmid,t_alem$cited_pmid))
t_list[[2]] <- unique(union(t_imat$cited_pmid,t_imat$citing_pmid))
t_list[[3]] <- unique(union(t_nela$cited_pmid,t_nela$citing_pmid))
t_list[[4]] <- unique(union(t_ramu$cited_pmid,t_ramu$citing_pmid))
t_list[[5]] <- unique(union(t_suni$cited_pmid,t_suni$citing_pmid))
library(SuperExactTest)
total <- length(t_list[[1]])+length(t_list[[2]])+length(t_list[[3]])+length(t_list[[4]])+length(t_list[[5]])
t_test <- supertest(t_list)
t_test$set.names <- c("alem","imat","nela","ramu","suni")