ericFormat <- function(t) {
# this function takes a list as input and generates a data frame 
# with four columns as output. The input list is generated by 
# an entrez_summary function that in turn takes an input vector of pmids
# to generate a list as ouput.

	a <- unname(sapply(t, function(x) x$uid))
	b <- unname(sapply(t, function(x) x$pubdate))
	c <- unname(sapply(t,function(x) x$sortfirstauthor))
	d <- unname(sapply(t, function(x) x$lastauthor))
	e <- unname(sapply(t, function(x) x$fulljournalname))
	f <- unname(sapply(t,function(x) x$title))
	g <- as.integer(substring(b,1,4))
	h <- data.frame(cbind(a, b, c, d, e, f,g), stringsAsFactors = FALSE)
		colnames(h) <- c("id","pubdate","firstauthor","lastauthor","source","title","year")
	return(h)
}